# Generated by Django 5.0.6 on 2024-05-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=10, unique=True, verbose_name='Бортовой номер')),
                ('model', models.CharField(max_length=50, verbose_name='Модель самосвала')),
                ('max_capacity', models.FloatField(verbose_name='Максимальная грузоподъемность (тонн)')),
                ('current_load', models.FloatField(verbose_name='Текущая нагрузка (тонн)')),
                ('sio2_content', models.FloatField(verbose_name='Содержание SiO2 (%)')),
                ('fe_content', models.FloatField(verbose_name='Содержание Fe (%)')),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=256, verbose_name='Название склада')),
                ('pre_unloading_volume', models.FloatField(verbose_name='Объем до разгрузки (тонн)')),
                ('after_unloading_volume', models.FloatField(verbose_name='Объем после разгрузки (тонн)')),
                ('sio2_content', models.FloatField(verbose_name='Содержание SiO2 (%)')),
                ('fe_content', models.FloatField(verbose_name='Содержание Fe (%)')),
                ('polygon_wkt', models.TextField(verbose_name='Полигон склада (WKT)')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='UnloadingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(verbose_name='Объем разгрузки (тонн)')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('inside_polygon', models.BooleanField(verbose_name='Попал в полигон')),
                ('dumptruck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumptrack.dumptruck', verbose_name='Самосвал')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumptrack.stock', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Событие разгрузки',
                'verbose_name_plural': 'События разгрузки',
            },
        ),
    ]
